### ISSUE TITLE
TypeError: dataclass() got an unexpected keyword argument 'kw_only'

### ISSUE THREAD

**Issue by LovesickDev** [joeyagreco/pythontextnow#26]
Not sure what is causing this, but when I import the module, this error appears.

`06.02 15:00:36 [Bot] Traceback (most recent call last):
06.02 15:00:36 [Bot] File "/sms.py", line 1, in <module>
06.02 15:00:36 [Bot] from pythontextnow import Client
06.02 15:00:36 [Bot] File "/.local/lib/python3.8/site-packages/pythontextnow/__init__.py", line 1, in <module>
06.02 15:00:36 [Bot] from .api.Client import Client
06.02 15:00:36 [Bot] File "/.local/lib/python3.8/site-packages/pythontextnow/api/Client.py", line 10, in <module>
06.02 15:00:36 [Bot] @dataclass(kw_only=True)
06.02 15:00:36 [Bot] TypeError: dataclass() got an unexpected keyword argument 'kw_only'`

I am using Pebblehost to run this code (a server). It works on my local machine and I've contacted Pebblehost support, but they told me this is a module thing and that I should report this as an issue here.

**Comment by LovesickDev** [comment]
Same error with Py 3.9 as well

**Comment by joeyagreco** [comment]
This library uses Python 3.10.

**Comment by Lieber0402** [comment]
@joeyagreco Just like he said, I met this error when I was using the Python 3.7 3.8 3.7, after I changed to the python 3.10, the error disappeared.
