### ISSUE TITLE
Incorrect SID?

### ISSUE THREAD

**Issue by robertsw22** [joeyagreco/pythontextnow#33]
I'm getting: "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url" when trying to send a message. I pulled the SID from the Application/Cookies section of the developer tab on Chrome. I couldn't find an request header mentioning "connect.sid". Would you mind taking screenshots on chrome when you get the chance?

**Comment by salvecom333** [comment]
i found the connect sid, but this is not working. i get the following error:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.textnow.com/api/users/salvadormontoya330/messages
![error](https://github.com/joeyagreco/pythontextnow/assets/44714713/8cb98e32-5d93-4075-8b10-a62dbc51763e)


i have tried with the firefox sid and the chrome sid, they both don't work, How can i resolve this, so i can get it to work?

**Comment by robertsw22** [comment]
Spare yourself the time and just use Twilio or something. This doesn't work anymore—wasted a solid day on it.
________________________________

**Comment by salvecom333** [comment]
thank you i wasted like 3 or 4 hours to get this to work, thanks for the heads up

**Comment by CometSb** [comment]
actually its super easy to make. 
just send the request.
all you will need is your cookie... Spending all day on something so simple. 
It took me 10 mins to copy headers and json and it works fine. ill make a repo. 
50 stars and ill release it

**Comment by joeyagreco** [comment]
Working as expected.
If this issue persists, please send a code snippet with error logs included and steps to reproduce.

**Comment by vake** [comment]
> Spare yourself the time and just use Twilio or something. This doesn't work anymore—wasted a solid day on it.


It works for me as of today. You just need to get the correct "connect.sid'
